apiVersion: v1
kind: ConfigMap
metadata:
  name: extended-oas
data:
  manualroutes.json: |
    {
      "paths": {
        "/hello": {
          "get": {
            "x-permission": {
              "allow": "allow_all"
            }
          }
        }
      }
    }
