apiVersion: v1
kind: ConfigMap
metadata:
  name: extended-oas
data:
  manualroutes.json: |
    {
      "paths": {
        "/hello": {
          "get": {
            "x-permission": {
              "allow": "allow_all"
            }
          }
        },
        "/secret-hello": {
          "get": {
            "x-permission": {
              "allow": "verify_authorization"
            }
          }
        },
        "/generate-request-filter": {
          "get": {
            "x-permission": {
              "allow": "data_filter",
              "resourceFilter": {
                "rowFilter": {
                  "enabled": true,
                  "headerKey": "x-acl-rows"
                }
              }
            }
          }
        },
        "/basic-info": {
          "get": {
            "x-permission": {
              "allow": "verify_authorization",
              "responseFilter": {
                "policy": "basic_info_parser"
              }
            }
          }
        }
      }
    }
